<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function getFindAllQuery($returnBuilder = false)
    {
        $qb = $this->createQueryBuilder('t')->select('t');

        return $returnBuilder ? $qb : $qb->getQuery();
    }
}
